[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "project-template"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter",
    "ipykernel",
    "pandas",
    "polars",
    "marimo>=0.17.7",
    "ruff>=0.14.3",
    "plotly>=6.4.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.2",
    "altair>=5.5.0",
    "snowflake-connector-python>=4.0.0",
]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
default = true

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.18",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
]